### ISSUE TITLE
add back EPUB support

### ISSUE THREAD

**Issue by quozl** [sugarlabs/read-activity#28]
EPUB support was [removed from Read](https://github.com/sugarlabs/read-activity/commit/69769eed93b99a0d1cd71823349c5adb418d3dd8) because of port complexity and nobody available to do it.

EPUB support could be added by either;
* reverting the commit and port the code to WebKit2 API,
* using Gepub via PyGObject introspection,
* using MuPDF.

Steps;
* [x] someone interested in doing this,
* [x] a separate branch, _epub_,
* [x] initial prototype,
* [x] testing by others,
* [ ] merge back into _master_ and release.

**Comment by quozl** [comment]
https://github.com/sugarlabs/read-activity/commit/c6dddebecfece9ad7e304c8248e5080abc5a2913

**Comment by samswag** [comment]
@quozl Any follow up on this? I see that almost all books from Get Book Activity doesn't work.

**Comment by quozl** [comment]
Are you testing with c6dddeb?  Have you a specific book you can point us at?

**Comment by samswag** [comment]
Not yet with c6dddeb, but I was trying to download "Journey to the Mysterious Island".

**Comment by quozl** [comment]
Thanks.  See the issue checklist above for current progress.  We're waiting on testing by others, and as you haven't tested c6dddeb yet, your report is not interesting, as we already know it doesn't work before that commit.  Please do test.

**Comment by aperezbios** [comment]
Confirmed working with sugar 0.112 on Fedora 28 SoaS

**Comment by quozl** [comment]
Thanks.
